### ISSUE TITLE
Backlog does not scroll to bottom after uploading attachment

### ISSUE THREAD

**Issue by plokk** [somia/ninchat-sdk-android#36] opened 2018-12-11 10:13 UTC
Only top of the attachment image is shown. It might be better to scroll to bottom. Or at least as far where uploaders name and timestamp can be seen.

Google Pixel Android 9 API 28
SDK: 0.2.5

**Comment by JussiPekonen-Qvik** [comment] 2018-12-12 13:12
Most likely the same root cause as in #36. Once that gets fixed this will get fixed too.

**Comment by JussiPekonen-Qvik** [comment] 2018-12-14 11:06
Fixed by the change done for #35.

**Closed by JussiPekonen-Qvik** 2018-12-14 11:06 UTC
