### ISSUE TITLE
Seconde video call dont open video

### ISSUE THREAD

**Issue by yehya73** [somia/ninchat-sdk-android#95] opened 2020-03-26 07:11 UTC
Android 6/7/9
Devices: Honor 7 lite / Galaxy edge S6 / Huawei P20 Lite
User starts a chat 
Operatore accept 
Operatore starts video call
User accept and then close with the red button
Opratore starts onther call 
User accepts
**Actual result:** after the user accept the video call, He wont see the caller but the caller see the user

**Comment by plokk** [comment] 2020-04-02 11:03
This exists also in Samsung Galaxy A8 running Android 9. This can be reproduced by following these steps:
- Initiate video call as agent
- End video call as agent
- Initiate another video call as agent

-> Agent can see their own video. Customer sees stopped videos from previous call and loading indicator on top of agents video.

If after this video call is stopped and agent initiates yet another video call, a video call view is not even displayed to the customer.

**Comment by plokk** [comment] 2020-04-02 11:08
This seems to be fixed in latest development version.

**Closed by plokk** 2020-04-02 11:08 UTC
Labels: Bug
