### ISSUE TITLE
Repeated message text is not displayed inside speech bubble

### ISSUE THREAD

**Issue by plokk** [somia/ninchat-sdk-android#45] opened 2018-12-11 10:45 UTC
This was reported by Kaisa. I don't have access to Android 7.0 atm.

"Lääkärin kirjoituksessa ensimmäinen viesti ok.
Tämän jälkeen lääkärin viestit eivät enää ole puhekuplan sisällä vaan sen alla."

SDK:n versio: uusin, 0.2.5
Käyttöjärjestelmän versio, Android 7.0
Laitteen malli, Galaxy A3 (2016)

**Comment by JussiPekonen-Qvik** [comment] 2018-12-11 13:49
The repeated messages **are** shown within the bubble:
![continued-agent-messages](https://user-images.githubusercontent.com/15980009/49804762-1cfd9700-fd5c-11e8-939e-42fd76e71c6e.png)

Is the repeated message bubble defined as specified in the README?

**Comment by plokk** [comment] 2018-12-11 13:52
Two people have said that this occurs in Android 7.0 but not in 9.0. At the moment this is all the information we have. Will investigate further.

**Comment by JussiPekonen-Qvik** [comment] 2018-12-11 14:03
I tested on Android 7.0 emulator using the default repeated bubble and this issue was not observed. I will test on a real Android 7.0 device tomorrow.

**Comment by JussiPekonen-Qvik** [comment] 2018-12-12 07:33
I would recommend that they test first if the text is inside the bubble when they do not override the repeated bubble asset. If the text is then inside the bubble, the issue is with their asset. If it is not, then this issue needs to be investigated.

**Comment by plokk** [comment] 2018-12-12 07:57
I tested this with Google Pixel emulator running Android 7.0. Could not reproduce. Maybe the problem is indeed with the replaced graphics.

**Comment by JussiPekonen-Qvik** [comment] 2018-12-14 11:47
Issue with the overridden resource definition. Will close this issue now.

**Closed by JussiPekonen-Qvik** 2018-12-14 11:47 UTC
Labels: question
